// Each group ends with the plain letter; the leading characters are marks that may stand in for it
export const diacriticsMarks = [
	"’'",
	'àâäåa',
	'éèêëe',
	'çc',
	'îíïi',
	'ñn',
	'öo',
	'šs',
	'ûüu',
	'ÿy',
];

// Copied from textlint-rule-diacritics (MIT, Artem Sapegin)
// That package exports only its entry point, so words.json cannot be imported
// Plurals and inflections are listed explicitly; the patterns use strict \b boundaries
export const diacriticsWords = [
	// French
	'beau idéal',
	'beaux idéals',
	'boutonnière',
	'boutonnières',
	'bric-à-brac',
	'café',
	'cafés',
	'cause célèbre',
	'causes célèbres',
	'chèvre',
	'chèvres',
	'cliché',
	'clichés',
	'comme ci comme ça',
	'consommé',
	'consommés',
	'coup d’état',
	"coups d'état",
	"coup d'états",
	'coup de grâce',
	'coups de grâce',
	'crudités',
	'crème brûlée',
	'crème brûlées',
	'crèmes brûlées',
	'crèmes brûlée',
	'crème de menthe',
	'crème fraîche',
	'crèmes fraîches',
	'crêpe',
	'crêpes',
	'débutante',
	'débutantes',
	'décor',
	'décors',
	'déjà vu',
	'déjà vues',
	'déjà vuing',
	'déjà vued',
	'dénouement',
	'dénouements',
	'façade',
	'façades',
	'fiancé',
	'fiancés',
	'fiancée',
	'flambé',
	'flambés',
	'garçon',
	'garçons',
	'lycée',
	'lycées',
	'maître d’',
	'maître d’s',
	'ménage à trois',
	'ménages à trois',
	// Local additions; upstream has no `ï` group so it cannot derive these
	'naïve',
	'naïveté',
	'naïvety',
	'négligée',
	'négligées',
	'papier-mâché',
	'protégé',
	'protégés',
	'protégée',
	'protégées',
	'purée',
	'purées',
	'puréeing',
	'puréed',
	'raison d’être',
	"raisons d'être",
	"raison d'êtres",
	// Bare "résumé" would match "resume processing", so each form carries a determiner
	'my résumé',
	'your résumé',
	'his résumé',
	'her résumé',
	'my résumés',
	'your résumés',
	'his résumés',
	'her résumés',
	'a résumé',
	'the résumé',
	'risqué',
	'roué',
	'roués',
	'soirée',
	'soirées',
	'soufflé',
	'soufflés',
	'soupçon',
	'soupçons',
	'touché',
	'tête-à-tête',
	'tête-à-têtes',
	'voilà',
	'à la carte',
	'à la mode',
	'émigré',
	'émigrés',

	// Spanish
	'el niño',
	'el niños',
	'jalapeño',
	'jalapeños',
	'la niña',
	'la niñas',
	'piña colada',
	'piña coladas',
	'señor',
	'señores',
	'señora',
	'señoras',
	'señorita',
	'señoritas',

	// Portuguese
	'açaí',
	'açaís',

	// German
	'doppelgänger',
	'doppelgängers',
	'führer',
	'führers',
	'gewürztraminer',
	'gewürztraminers',
	'übermensch',
	'übermenschen',

	// Latin
	'vis-à-vis',

	// Swedish
	'filmjölk',
	'smörgåsbord',

	// Names, places, and companies
	'beyoncé',
	'brontë',
	'champs-élysées',
	'citroën',
	'curaçao',
	'häagen-dazs',
	'löwenbräu',
	'monégasque',
	'mötley crüe',
	'nescafé',
	'queensrÿche',
	'québec',
	'québécois',
	'ångström',
	'škoda',
];
